### ISSUE TITLE
Why were the patch versions for CVE-2022-39304 released so late?

### ISSUE THREAD

**Issue by Silence-worker-02** [bradleyfalzon/ghinstallation#104]
Hello, we are a research team working on Golang. During our investigation, we found CVE-2022-39304 was addressed in commit d24f14f8be70d94129d76026e8b0f4f9170c8c3e. However, we noticed that the patch version was released after long time (60 days).  We are curious about the reasons behind the delayed release of the patch version, as it may hinder the efficient distribution of patches to downstream users. Could the reason be 

1.Issues with testing and CI checking. 

2.Other commits have to be incorporated into one release. 

3.By convention, versions are not frequently released. 

4.Other reasons. 

Thank you for your attention, and we look forward to receiving your reply.

**Comment by bradleyfalzon** [comment]
Hi,

Just to clarify, The CVE was publically disclosed on Dec 20, 2022, the issue was raised with us on Sep 6, 2022, but it was actually patched in Mar 9, 2021 - the delay was purely me not clicking "make public" after it was issued on Oct 14, 2022.

- Fixed: Mar 9, 2021
- Raised: Sep 6, 2022
- Issued: Oct 14, 2022
- Publically Disclosed:  Dec 20, 2022
