### ISSUE TITLE
int64 for appID/installationID

### ISSUE THREAD

**Issue by dinvlad** [bradleyfalzon/ghinstallation#27]
Hi @bradleyfalzon and @wlynch,

I noticed the discussion re `int64` in https://github.com/google/go-github/issues/597, however `ghinstallation` accepts `appID/installationID` as regular `int` for initialization.

What would be your recommendation if I'd like to initialize `ghinstallation` based on `appID/installationID` from `github.InstallationEvent`? Currently, we have to downcast `int64`→ `int` to make it compatible with `ghinstallation`...

Thanks!

**Comment by wlynch** [comment]
I'm in favor of bumping it to int64 to match the rest of go-github, especially since there have been [reported cases](https://github.com/google/go-github/issues/597#issuecomment-351854522) where int has caused problems.

My one hesitation is that this would be a breaking change for anyone currently doing the int cast (which I suspect given the go-github types is quite a few).

@bradleyfalzon Breaking changes are something that comes up fairly frequently. One option would be to introduce [Go modules](https://github.com/golang/go/wiki/Modules) to the library to enable semver so that users wanting stability can pin to a version. wdyt?

**Comment by bradleyfalzon** [comment]
I think we should make the change from `int` to `int64` for the same reasons go-github chose to, and for keeping some consistency with go-github as this library is likely heavily used with it.

As for the breaking change, I'm fine with this, see discussion in #28 for my initial thoughts on how to get there.

**Comment by bradleyfalzon** [comment]
@dinvlad are you using Go modules in your project currently?

To answer your question, for now convert from `int64` to `int` as you probably are already.

We'll release a breaking change and bring this library up to `v1.0.0` so you won't need to do that anymore.

**Comment by dinvlad** [comment]
@bradleyfalzon thanks, yes I do use 1.11 modules! To deploy it in Cloud Functions, I have to run `go mod vendor` though (because of peculiarities of private module resolution in GCF). Is that going to affect anything?

**Comment by bradleyfalzon** [comment]
It shouldn't, at least not what I know of. What's the relevant lines in `go.mod` and `go.sum` for ghinstallation?

**Comment by dinvlad** [comment]
Mine says `require github.com/bradleyfalzon/ghinstallation v0.1.2` and
```
github.com/bradleyfalzon/ghinstallation v0.1.2 h1:9fdqVadlvEX/EUts5/aIGvx2ujKnGNIMcuCuUrM6s6Q=
github.com/bradleyfalzon/ghinstallation v0.1.2/go.mod h1:VQsLlCoNa54/CNXcc2DuCfNZrZxqQcyPeqKUugF/2h8=
```
